/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4ee6b7a9-3f96-4562-b29a-b8abf117445a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nalUA8qYb",
    "aws_user_pools_web_client_id": "4edkolne3dlv6poj5r4ncvhsbp",
    "oauth": {}
};


export default awsmobile;
